### ISSUE TITLE
Monitoring SAT calls while solving the first order problem

### ISSUE THREAD

**Issue by puneet19189** [stp/stp#408] opened 2021-07-25 04:50 UTC
Hi
We are working on comparing the speed of SAT and SMT. We want to see how many times SAT is being called while solving the problem because the whole idea of SMT solvers is to do theory-specific processing beforehand hence it should have reduced the number of SAT calls.
How can we monitor and benchmark the same?
Any suggestions and advice will be helpful.

**Comment by andrewvaughanj** [comment] 2021-07-25 07:51
Hi,

I think you might need to elaborate a bit on what you're doing, but your question doesn't make _exact_ sense when talking about STP.

Are you believing that STP implements a CDCL(T)-type loop (e.g., using a propositional abstraction to send to the SAT solver and then collaborating theory solvers on top of that)? Because, unlike a *a lot* of other SMT solvers, this isn't how STP works and STP does things *extremely* eagerly.

For pure bit-vector problems, STP will call the SAT solver *once* (for the non-incremental case) -- it will attempt to simplify and rewrite the problem (and may not call the SAT solver at all!), but there is no "loop" for QF_BV.

For QF_ABV (importantly: **without extensionality, which STP does not support**), then STP may interact with the solver multiple times, but not a way that is normal if you're used to CDCL(T) -- [STP changes reads/writes into propositions](https://ece.uwaterloo.ca/~vganesh/Publications_files/vg2007-STP-CAV.pdf), calls the SAT solver, and then based on that response may either return SAT, UNSAT or add new read/write propositions and re-call the SAT solver. In this instance, on SMT-level `assert` might become multiple SAT solver checks (same with CDCL(T)).

So, based on this, what do you *really* want to see? Still the number of times that STP called the SAT solver and got SAT/UNSAT (or unknown if have timeouts)?

If so, call STP with `-t`, which will print the statistics, including the number of times the SAT solver was called.

Cheers,

Andrew

**Comment by msoos** [comment] 2021-07-25 16:33
Hi!

First of all 100% what Andrew said. Secondly, just one more thing. You said: `hence it should have reduced the number of SAT calls`. That's not necessarily true. The aim is to reduce the amount of time to solve a problem. That may mean that we *increase* the number of SAT calls, as we may be able to solve an instance faster if we call the SAT solver multiple times, quickly, rather fewer times, slowly. Please beware that not all SAT calls are equivalent. Some are *much* harder than others, and a smart SMT solver will do the best guess in how to translate the problem & solve it, optimizing for overall time, rather than the number of SAT calls.

Just my 2 cents,

Mate

**Comment by andrewvaughanj** [comment] 2021-07-29 21:32
@puneet19189 do you need any more help or can we close this issue?

**Comment by puneet19189** [comment] 2021-07-30 00:56
Hi

Yes please close the issue. If more help needed I will reopen.

Regards
Puneet Kumar

**Comment by puneet19189** [comment] 2021-08-01 11:31
Thanks for the answers guys. @andrewvaughanj as you said using -t we can monitor the SAT calls. How to do that using the C API . Let's take the example file provided with the STP (example.c in the directory STP/examples/simple), can you please tell me what changes to make so that we get the statistics after the execution of this code

**Comment by andrewvaughanj** [comment] 2021-08-01 13:37
Do you want to print it, or do you want the value programmatically?

Currently, you should be able to do:

```
bm = new STPMgr();
bm->GetRunTimes()->print();
```

which will print it to stdout, *but* if you need that programmatically, it doesn't exist currently.

If you want to do this, you need access to `std::map<Category, int> counts` in `class RunTimes` and then you want the key-value pair for `RunTimes::Solving`.

**Comment by RaiyyanMalik** [comment] 2021-08-14 19:08
I am also working on SAT solving and specifically using STP. I have read the paper mentioned in the above comment (https://ece.uwaterloo.ca/~vganesh/Publications_files/vg2007-STP-CAV.pdf). I wanted to know that in the paper, it is mentioned that while solving one of the three cases, when the abstract formula is unsatisfiable, then the STP doesn't call the SAT and return unsatisfiable without any refinements. 

So, I wanted to check if the STP is solving the unsatisfiable cases without invoking the SAT. To know this, I have tried the mentioned commands to get the number of SAT calls.

bm = new STPMgr();
bm->GetRunTimes()->print();

However, these commands are not working as they should. Some segmentation faults are occurring. Also, by looking into the definitions, GetRunTimes() actually prints the run time and not the number of times the SAT is being invoked.

Please provide any help on how we can check how many times SAT is called when proving the formulas. It will be really helpful to know STP better and how it is solving unsatisfiable cases.

Thanks & Regards
Raiyyan

**Comment by andrewvaughanj** [comment] 2021-08-15 15:49
My apologies, I hadn't realised we weren't including the C++ API as part of `make install` -- given this, I'm not actually sure how you're using the C++ API, but it certainly isn't "safe for consumption". I actually don't know what you've done to be able to call `new STPMgr` from outside of STP, but it likely not to be correct.

While I don't consider this "ready to merge", I exposed this functionality for you here:

- https://github.com/stp/stp/compare/master...andrewvaughanj:c_api_print_stats

**Please note**: all this does is allow you to call `bm->GetRunTimes()->print()` from the C API -- it still dumps stuff to stderr and it doesn't allow you to "query" what runtimes you want to see.

This should allow you to experiment with what you're after (in terms of checking how many SAT calls have been made).

> Also, by looking into the definitions, GetRunTimes() actually prints the run time and not the number of times the SAT is being invoked.
>

This is incorrect; these lines:

-
- https://github.com/stp/stp/blob/60b80d3af9e3835c7c9b70f375f11b3427a20d69/lib/Util/RunTimes.cpp#L76-L81

Prints the count (`it1`) and the duration (`it2`).

**Comment by RaiyyanMalik** [comment] 2021-08-16 18:22
Thanks a lot for helping. I also thought that including C++ API along with C API was not the right way. 

I have tried to Integrate the changes that you have just made, but an error of undefined reference is coming mentioned below.

> undefined reference to `vc_printRunTimes'

If you could show how to use the function in the simple example.c from the STP directory. That will solve the problem most efficiently.

Thanks & Regards
Raiyyan

**Comment by andrewvaughanj** [comment] 2021-08-16 18:43
> If you could show how to use the function in the simple example.c from the STP directory. That will solve the problem most efficiently.

The example is here:

- https://github.com/andrewvaughanj/stp/blob/b873a04cdece9aa1aa14653adb37d9ae0833fa6e/tests/api/C/sat_calls.cpp#L34

but you need to be linking against a build of that branch (so not master).

**Comment by andrewvaughanj** [comment] 2021-08-19 12:10
@RaiyyanMalik did this work for you?

**Comment by RaiyyanMalik** [comment] 2021-08-19 12:34
Yes, It worked! Successfully Printed the stats. 
Thanks a lot for helping.

**Comment by andrewvaughanj** [comment] 2021-08-19 12:41
Is this "good enough" for you, or would you actually like an API to get access to this information "programmatically"?

Given what I wrote spits stuff out to stderr, I am not sure it is worth merging with master.

**Comment by RaiyyanMalik** [comment] 2021-08-19 13:22
Yes, it is good enough. No need to merge with the Master.

**Comment by RaiyyanMalik** [comment] 2021-08-25 16:44
Hi again,

I'm trying to build stp using only cryptominisat as the SAT solver. It is not building and giving cmake error. 

Please guide me if it is possible to build stp like this or require minisat as a mandatory SAT solver. I wanted to use cryptominisat as the SAT solver and then wanted to see the Statistics.

The given steps suggests that stp supports other SAT solvers, please suggest how to use other SAT solvers other than minisat.

Thanks & Regards
Raiyyan

**Comment by andrewvaughanj** [comment] 2021-08-25 16:51
> It is not building and giving cmake error.
>

Can you please tell us _what_ it is saying? I don't really have much to go on here ...

**Comment by RaiyyanMalik** [comment] 2021-08-25 16:53
[ 96%] Linking CXX executable ../../stp
/usr/bin/ld: ../../lib/libstp.so.2.3: undefined reference to `Minisat::SimpSolver::addClause_(Minisat::vec<Minisat::Lit, int>&)'
/usr/bin/ld: ../../lib/libstp.so.2.3: undefined reference to `Minisat::Solver::addClause_(Minisat::vec<Minisat::Lit, int>&)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/stp/CMakeFiles/stp-bin.dir/build.make:105: stp] Error 1
make[1]: *** [CMakeFiles/Makefile2:1128: tools/stp/CMakeFiles/stp-bin.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by RaiyyanMalik** [comment] 2021-08-31 18:27
Hi,

I was wondering, is it possible to quantify the pre-processing happening in the stp.

Let's say how many variables are eliminated during Variable elimination. Can we check the number of variables before and after this Process?

Finally, I wanted to check how much the pre-processing (or Theory Specific Reasoning) affecting the solving time for SAT.

For example, I don't want stp to do the Bitvector Solving or Variable elimination or any one of the processing and see how much time the SAT uses to solve without that particular processing taking place.


Thanks & Regards 
Raiyyan

**Comment by andrewvaughanj** [comment] 2021-08-31 18:46
If you want to answer these questions, you're going to need to start poking around STP's internals yourself.

You should play around in `STP::TopLevelSTPAux` to enable/disable the kind of simplifications/transformations you care about.

I warn you though: some simplifications are *required* and if you end-up removing them, you might pass terms to the bit-blaster that it doesn't know how to translate into a propositional formula, and then you're going to get a lot of assertion errors.

**Comment by andrewvaughanj** [comment] 2021-11-11 16:36
Can you share an example of your SMT queries that "get larger"? Are these using any "theories" or are they only Boolean problems? Are they already converted to CNF?

**Comment by RaiyyanMalik** [comment] 2021-11-11 16:52
It is not a Boolean problem but rather a Bit vector problem. We have implemented a three-valued logic.

For SAT: I am directly making the CNF and passing it to the SAT solver to solve.
For SMT: I first convert the problem into expressions and after CNF conversion, which is internal to STP, then check the number of clauses and variables.

So, for SAT, the problem is already converted to CNF.
For SMT, it is converted to CNF by the STP internally.

**Comment by andrewvaughanj** [comment] 2021-11-11 16:59
So what you're saying is that in some instances STP makes more variables than your hand-translation does? I don't consider that surprising, because that's how some simplifications work (e.g., it is cheaper to make more variables with simpler clauses than fewer variables with harder clauses).

**Comment by RaiyyanMalik** [comment] 2021-11-11 17:32
Yes, that is what I was saying.

So, STP simplifies in 2 ways depending on the problem.

It simplifies by reducing the variables (which is happening in the majority of the cases),
and It simplifies by increasing the variables also (which is happening in a minority of the cases).

**Comment by andrewvaughanj** [comment] 2021-11-11 17:34
If you share an example of something where you're surprised at the increase in the number of variables, then I can take a look.

Without that, it is hard to make guesses about what's "wrong".

**Closed** 2022-05-13 06:05 UTC
