### ISSUE TITLE
running `make` without `make AST` first fails

### ISSUE THREAD

**Issue by kovach** [stp/stp#192] opened 2015-07-23 21:20 UTC
build fails because AST/ASTKind is not present; building the AST target first works though.

I'm using cmake 3.0.2 on osx.

**Comment by msoos** [comment] 2015-07-23 21:32
Hey! Thanks for that! Can you please delete your generated AST header and try to re-produce the make output with: "make VERBOSE=1" when it fails? I'd need to know how it went.

Thanks a lot in advance,

mate

**Comment by msoos** [comment] 2015-08-27 23:55
I looked at every target. All that needs the ASTKind.h seems to require it. I cannot reproduce it using the ZIP file and then trying to "make" single-threaded as described in the bugreport. The original reporter is not available for comment :( So I must close this. Sorry!

**Comment by andreamattavelli** [comment] 2017-07-27 20:30
Hi,
the issue seems to be still present when STP is compiled in our Travis-CI Mac OS builds: https://github.com/klee/klee/issues/714

**Comment by delcypher** [comment] 2017-07-27 20:37
I identified the issue and mentioned it in the KLEE issue but I'll repeat it here for completeness

The bug is here https://github.com/stp/stp/blob/master/lib/Parser/CMakeLists.txt . There's a missing dependency on the ASTKind_header target (declared in https://github.com/stp/stp/blob/master/lib/AST/CMakeLists.txt) . This isn't the best fix though. There's no reason the header (and corresponding cpp file) need to be built at build time though. This can be done at configure time instead which will fix the race and will allow the build system to be cleaned up. To make this work though the configure needs to be made dependent on the files the generate the header and cpp file (i.e. the pearl script and the files it consumes) so that changes to those forces a reconfigure.

This can be achieved by setting the CMAKE_CONFIGURE_DEPENDS property on the lib/AST directory and adding to the list the perl script and the file it consumes.

**Comment by msoos** [comment] 2017-08-06 19:43
Good work identifying the underlying issue! Dan, do you know what needs to be done to fix it? Can you take a shot at it?

**Comment by delcypher** [comment] 2017-08-06 19:45
> Good work identifying the underlying issue! Dan, do you know what needs to be done to fix it? Can you take a shot at it?

Sure. I know how to fix it.

**Comment by msoos** [comment] 2017-08-06 19:50
:) Cool! Can you give it a shot? I'm going a little crazy over CMake -- though I have learnt a lot about generator expressions, etc. so I'll fix up cmake for STP soon. CMS has been fixed up a lot already. Thanks!

**Comment by delcypher** [comment] 2017-08-06 20:36
@msoos I've created PR #265 . Let's make sure it builds properly before merging. In the end I went for the simpler change because my alternative approach had some unforeseen problems. I could have worked around them but I thought it made the build system too complicated so I went for the simpler approach.

**Closed by delcypher** 2017-08-06 20:36 UTC

**Comment by msoos** [comment] 2017-08-06 20:48
Worked for me. I think it's OK. I will make the build pass soon (CMS is an issue + STP had some issues in the past too, all being fixed now)
