### ISSUE TITLE
stp cms5 lib dependency error when linked into klee

### ISSUE THREAD

**Issue by humeafo** [stp/stp#288] opened 2018-03-29 10:03 UTC
you can see ld failed with -llibcryptominisat5 commandline, and this should be -lcryptominisat5, and this is caused by the generated STPTargets.cmake

```
set_target_properties(libstp PROPERTIES
  INTERFACE_LINK_LIBRARIES "/usr/local/lib/libboost_program_options.a;/usr/local/lib/libminisat.a;libcryptominisat5;/usr/lib/x86_64-linux-gnu/libm4ri.a"
)
```

I think here full libcryptominisat5 path or just cryptominisat5 should all be ok, this maybe caused by the usage in CMakelists.txt in stp? I haven't investigate this much yet.
my env is Ubuntu 16.04 with cmake version 3.5.1.

**Comment by msoos** [comment] 2018-04-02 04:48
Hi! Sorry for the late reply. Can you please give a full output? What you wrote is a bit confusing and it'd be really nice to see the full cmake and build output. Please run both `cmake ..` and `make VERBOSE=1` again, in an empty build directory so we can see all the output :) Thanks!

**Comment by humeafo** [comment] 2018-04-10 03:27
sorry for the late response, the make VERBOSE=1 related error is as follows:

[ 79%] Linking CXX executable ../../bin/gen-random-bout
cd /home/cuser/mdev/symexec/klee/build362/tools/gen-random-bout && /usr/bin/cmake -E cmake_link_script CMakeFiles/gen-random-bout.dir/link.txt --verbose=1
/usr/bin/c++    -Wall -Wextra -Wno-unused-parameter -O2 -g   CMakeFiles/gen-random-bout.dir/gen-random-bout.cpp.o  -o ../../bin/gen-random-bout -rdynamic ../../lib/libkleeBasic.a ../../lib/libkleaverSolver.a ../../lib/libkleeBasic.a ../../lib/libkleaverSolver.a ../../lib/libkleaverExpr.a ../../lib/libkleeSupport.a /usr/local/lib/libz.so -ltcmalloc /home/cuser/devlibs/llvm362/lib/libLLVMSupport.a -lrt -ldl -ltinfo -latomic -lpthread -lz -lm -lrt -ldl -ltinfo -latomic -lpthread -lz -lm /usr/local/lib/libstp.a /usr/local/lib/libboost_program_options.a /usr/local/lib/libminisat.a -llibcryptominisat5 -Wl,-Bstatic -lm4ri -Wl,-Bdynamic /usr/local/lib/libz3.so -Wl,-rpath,/usr/local/lib:
**_/usr/bin/ld: cannot find -llibcryptominisat5_**
collect2: error: ld returned 1 exit status
tools/gen-random-bout/CMakeFiles/gen-random-bout.dir/build.make:108: recipe for target 'bin/gen-random-bout' failed
make[2]: *** [bin/gen-random-bout] Error 1
make[2]: Leaving directory '/home/cuser/mdev/symexec/klee/build362'
CMakeFiles/Makefile2:697: recipe for target 'tools/gen-random-bout/CMakeFiles/gen-random-bout.dir/all' failed
make[1]: *** [tools/gen-random-bout/CMakeFiles/gen-random-bout.dir/all] Error 2
make[1]: Leaving directory '/home/cuser/mdev/symexec/klee/build362'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by msoos** [comment] 2018-04-10 03:56
Thanks, I see! Can you please include the generated  STPTargets.cmake here please? For me the generated one looks like:

```
# Config file for the installed STP Package
# It defines the following variables
#  STP_INCLUDE_DIRS - include directories for STP
#  STP_STATIC_LIBRARY - static library target (empty if not built)
#  STP_SHARED_LIBRARY - dynamic library target (empty if not built)
#  STP_EXECUTABLE     - the stp executable
#  STP_VERSION_*      - the stp MAJOR/MINOR/PATCH versions
#  STP_VERSION        - the stp complete version string

# Compute paths
get_filename_component(STP_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(STP_INCLUDE_DIRS "/usr/local/include")

# Our library dependencies (contains definitions for IMPORTED targets)
include("${STP_CMAKE_DIR}/STPTargets.cmake")

# These are IMPORTED targets created by STPTargets.cmake
set(STP_EXECUTABLE stp)

set(STP_STATIC_LIBRARY libstp)
set(STP_SHARED_LIBRARY libstp)

# Note version variables are implicitly set by STPConfigVersion.cmake
```

For CryptoMiniSat the same thing looks like:
```
# Config file for the Build-tree cryptominisat Package
# It defines the following variables
#  CRYPTOMINISAT5_INCLUDE_DIRS - include directories for cryptominisat5
#  CRYPTOMINISAT5_LIBRARIES    - libraries to link against
#  CRYPTOMINISAT5_EXECUTABLE   - the cryptominisat executable

# Compute paths
get_filename_component(CRYPTOMINISAT5_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(CRYPTOMINISAT5_INCLUDE_DIRS "/home/soos/development/sat_solvers/cryptominisat/build/include")

# Our library dependencies (contains definitions for IMPORTED targets)
include("${CRYPTOMINISAT5_CMAKE_DIR}/cryptominisat5Targets.cmake")

# These are IMPORTED targets created by cryptominisat5Targets.cmake
set(CRYPTOMINISAT5_LIBRARIES libcryptominisat5)
set(CRYPTOMINISAT5_LIBRARIES_IPASIR ipasircryptominisat5)
set(CRYPTOMINISAT5_STATIC_LIBRARIES libcryptominisat5)
set(CRYPTOMINISAT5_STATIC_LIBRARIES_IPASIR ipasircryptominisat5)
set(CRYPTOMINISAT5_STATIC_LIBRARIES_DEPS /usr/local/lib/libm4ri.so)
set(CRYPTOMINISAT5_VERSION_MAJOR 5)
set(CRYPTOMINISAT5_VERSION_MINOR 2)
set(CRYPTOMINISAT5_EXECUTABLE cryptominisat5)
```

All of these seem reasonable. Can you please include yours? Thanks!

**Comment by humeafo** [comment] 2018-04-10 09:37
$cat /usr/local/lib/cmake/STP/STPTargets.cmake

# Generated by CMake 3.5.1

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget libstp stp stp_simple)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Create imported target libstp
add_library(libstp STATIC IMPORTED)

set_target_properties(libstp PROPERTIES
  INTERFACE_LINK_LIBRARIES "/usr/local/lib/libboost_program_options.a;/usr/local/lib/libminisat.a;**_libcryptominisat5;_**/usr/lib/x86_64-linux-gnu/libm4ri.a"
)

# Create imported target stp
add_executable(stp IMPORTED)

# Create imported target stp_simple
add_executable(stp_simple IMPORTED)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/STPTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)

**Comment by humeafo** [comment] 2018-04-10 09:38
cat /usr/local/lib/cmake/cryptominisat5/cryptominisat5Targets.cmake
# Generated by CMake 3.5.1

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ipasircryptominisat5 libcryptominisat5 cryptominisat5_simple cryptominisat5)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Create imported target ipasircryptominisat5
add_library(ipasircryptominisat5 STATIC IMPORTED)

set_target_properties(ipasircryptominisat5 PROPERTIES
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libm4ri.a;libcryptominisat5"
)

# Create imported target libcryptominisat5
add_library(libcryptominisat5 STATIC IMPORTED)

set_target_properties(libcryptominisat5 PROPERTIES
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libm4ri.a;-pthread"
)

# Create imported target cryptominisat5_simple
add_executable(cryptominisat5_simple IMPORTED)

# Create imported target cryptominisat5
add_executable(cryptominisat5 IMPORTED)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/cryptominisat5Targets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)

**Comment by humeafo** [comment] 2018-04-10 09:43
and the local STPTargets.cmake seems fine in stp build directory.

buildstp$ cat STPTargets.cmake
set_target_properties(libstp PROPERTIES
  INTERFACE_LINK_LIBRARIES "/usr/local/lib/libboost_program_options.a;/usr/local/lib/libminisat.a;cryptominisat5;/usr/lib/x86_64-linux-gnu/libm4ri.a"
)

**Comment by kren1** [comment] 2019-02-07 21:44
Can +1 this issue. My workaround was to rename `libcryptominisat5.so` to `liblibcryptominisat5.so`, but something is obviously off.

**Comment by msoos** [comment] 2019-02-08 20:19
Ooops, you are both right. I can now confirm the issue. I am trying to fix as we speak :)

**Comment by msoos** [comment] 2019-02-08 21:16
Yes! I think I have managed to fix it with the latest set of patches, current head ca1657a829f3e344dfbaf9bd30926f0065445d24 should be fine. Fixes in patches were:

ca1657a829f3e344dfbaf9bd30926f0065445d24
3cfa553feb1350e181ae2b43cf867fe499258a4b
db98db507e0aeff51a5be09b75d439c99bfb9e2f
ba12a11b21199c47f0ecd8bbcedb3145f208501d

Please take a look at the current master HEAD and let me know if it's good :) I believe it's good because I could reproduce the bug on my end and it has now disappeared :)

**Comment by kren1** [comment] 2019-02-09 14:16
Thanks! It is fixed for me as well!

**Comment by msoos** [comment] 2019-02-09 17:29
Thanks for confirming! And thanks for reporting! Closing :)

**Closed by msoos** 2019-02-09 17:29 UTC
Labels: build issue
