### ISSUE TITLE
Question about parameter "threads".

### ISSUE THREAD

**Issue by TraceShadow** [stp/stp#457] opened 2023-01-11 08:02 UTC
I saw your solver has a parameter called "threads", but it is in the "SAT Solver options". Does this mean that if I use this parameter, the smt file will be converted to cnf and use sat solver? If yes, how can I use the parallel for SMT solver with binary? Thanks a lot!

**Comment by rgov** [comment] 2023-01-11 15:41
Dupe of #456.

**Closed by rgov** 2023-01-11 15:41 UTC
