### ISSUE TITLE
Question about debugging wrong encoding

### ISSUE THREAD

**Issue by mikhailramalho** [stp/stp#394] opened 2021-02-01 23:06 UTC
Hi again,

I'm trying to debug some formulas that I'm encoding using STP but I can't seem to be able to print the formula or even print the individual expressions.

I've tried `vc_printExpr`, `vc_printExprCCode`,  `vc_printSMTLIB`, `vc_printExprToBuffer` to print the expression but I only seem to get the expression's address.

To print the whole formula, I've tried `vc_printAsserts` and `vc_printQuery` but STP aborts when trying to print an `UNDEFINED`, which seems like an indication that I messed up with the encoding...

Any suggestion on how I can proceed here?

**Comment by mikhailramalho** [comment] 2021-02-01 23:09
Nevermind about "printing the address", it's actually printing the correct constant.

**Comment by andrewvaughanj** [comment] 2021-02-01 23:10
So it is working for you? I would expect it to print the internal structure when you print it.

**Comment by andrewvaughanj** [comment] 2021-02-01 23:18
Hmm, actually, I realised the form I'm used to might be immediately accessible to you.

It isn't exposed via the API, but the implementation of `operator<<` for `ASTNode` is quite useful (more so, I feel, than `q.PL_Print`).

Try adding `std::cout << q << std::endl;` inside of `void vc_printExpr(VC vc, Expr e)`.

**Note**: there could be an element of Stockholm Syndrome here and the output of `<<` is actually terrible, it is just what I'm used to, so I like it 🤷

**Comment by andrewvaughanj** [comment] 2021-02-01 23:32
I just exposed something that might be useful to you:

- https://github.com/stp/stp/compare/master...andrewvaughanj:print_internal_repr

If you want this, I can look at getting it merged. If you're not fussed, then I won't (mainly because I don't like API methods that return `char*`).

**Comment by mikhailramalho** [comment] 2021-02-02 01:16
Thanks, @andrewvaughanj, I was able to pinpoint the issue I'm having to a bvextract, there's seem to be a mismatch on the expr size somehow:
```
(gdb) l
373	
374	SMTExprRef STPSolver::mkBVExtractImpl(unsigned High, unsigned Low,
375	                                      const SMTExprRef &Exp) {
376	  return newExprRef(
377	      STPExpr(Context, mkBVSort(High - Low + 1),
378	              STP::vc_bvExtract(*Context, toSolverExpr<STPExpr>(*Exp).Expr,
379	                                High, Low)));
380	}
381	
382	SMTExprRef STPSolver::mkBVConcatImpl(const SMTExprRef &LHS,
(gdb) call Exp->Sort->dump()
BITVECTOR(0000000A) 
(gdb) call Exp->Sort->getWidthFromSolver()
$1 = 10
(gdb) down
#8  0x00007ffff4639258 in vc_bvExtract (vc=0x41f780, ccc=0x431ac0, hi_num=8, low_num=8) at /home/mgadelha/tools/stp/lib/Interface/c_interface.cpp:1540
1540	  BVTypeCheck(o);
(gdb) l
1535	
1536	  stp::ASTNode hi = b->CreateBVConst(32, hi_num);
1537	  stp::ASTNode low = b->CreateBVConst(32, low_num);
1538	  stp::ASTNode o =
1539	      b->CreateTerm(stp::BVEXTRACT, hi_num - low_num + 1, *a, hi, low);
1540	  BVTypeCheck(o);
1541	  stp::ASTNode* output = new stp::ASTNode(o);
1542	  // if(cinterface_exprdelete_on) created_exprs.push_back(output);
1543	  return output;
1544	}
(gdb) call (*a)[0].GetValueWidth()
$2 = 8
```

Let me try to explain the output:
1. The code calls STP::vc_bvExtract, `High` is 9, `Low` is 9.
2. The size of the expression being passed to STP::vc_bvExtract is 10 (or BITVECTOR(0000000A)) as printed by STP.
3. The Expr in STP is converted (`stp::ASTNode* a = (stp::ASTNode*)ccc;`) and `(*a)[0].GetValueWidth()` returns 8.
4. The exception in `/home/mgadelha/tools/stp/lib/AST/ASTmisc.cpp:497` is thrown, because `(n[1].GetUnsignedConst() >= n[0].GetValueWidth())` holds. Here, `n[1].GetUnsignedConst()` is 9 and `n[0].GetValueWidth()` is 8.

The expr is:
```
1724:(BVEXTRACT 
  908:(ITE 
    766:(OR 
      268:(EQ 
        134:0b0000000000000000000000000000000
        256:(BVEXTRACT 
          52:f
          200:0x0000001D
          218:0xFFFFFFFF))
      762:(OR 
        244:(EQ 
          62:0xFF
          206:(BVEXTRACT 
            52:f
            200:0x0000001D
            204:0x00000016))
        728:(AND 
          269:(NOT [268])
          702:(EQ 
            116:0x00
            [206]))))
    894:0x80
    824:(BVCONCAT 
      808:(BVNOT 
        802:(BVEXTRACT 
          794:(BVPLUS 
            792:0x01
            [206])
          798:0x00000006
          798:0x00000006))
      816:(BVEXTRACT 
        [794]
        812:0x00000005
        218:0xFFFFFFFF)))
  56:0x00000008
  56:0x00000008)
```

Any ideas?

**Comment by andrewvaughanj** [comment] 2021-02-02 01:27
I’m not at my desk now ... I can look in the morning.

For your point 3, what has width 8? Your BV constant that was previously 10 (Point 2)?

In your dump, I don’t see 0xA — how does that align with Point 2?

**Comment by andrewvaughanj** [comment] 2021-02-02 21:35
@mikhailramalho is your `0xA` your expr above (i.e., `1724:(BVEXTRACT...`)?

Basically, I tried doing this directly with `0xA` (via `vc_bvConstExprFromInt`), but if I do an extract on this, it goes through the "constant evaluator" (as there's nothing to "reason about"), so I don't see your issue.

Can you create a self-contained example that reproduces this issue? If not, I can try to reproduce it based on your dump above (but I'm not even sure this is where the problem is).

**Comment by mikhailramalho** [comment] 2021-02-03 16:35
Hi @andrewvaughanj, I finally found the issue: I was using the `vc_bvSignExtend` in the wrong way.

```
//! \brief Returns a bitvector expression representing the extension of the given
//!        to the amount of bits given by 'newWidth'.
//!
//! Note: This operation retains the signedness of the bitvector is existant.
//!
DLL_PUBLIC Expr vc_bvSignExtend(VC vc, Expr child, int newWidth);
```

The documentation clearly states that we should pass the new bv width, whereas I was only passing how many bits I wanted to increase. I was trying to increase the length of a bv of size 8 to 10, but I was getting a bitvector of size 2.

May I suggest taking a look if the internal sort representation is updated after a sign extension? It seems that even when I get a new bv of size 2, the size was actually incremented to 10.

**Comment by andrewvaughanj** [comment] 2021-02-03 16:50
Yeah; that "what's the new size" thing isn't pretty 🤮

I'll take a look at the size thing and come back to you.

**Comment by andrewvaughanj** [comment] 2021-02-03 17:02
> May I suggest taking a look if the internal sort representation is updated after a sign extension? It seems that even when I get a new bv of size 2, the size was actually incremented to 10.
>

So I can't reproduce this ...

```
  Expr node = vc_varExpr1(vc, "node", 0, width);
  Expr ext = vc_bvSignExtend(vc, node, 2);
  std::cout << *(ASTNode*)ext << std::endl;
  std::cout << (*(ASTNode*)ext).GetValueWidth() << std::endl;
```

Gives 2 (as we expected), as well giving a `BVEXTRACT` node (rather than a `BVSX`, because the "new width" is less than the original width).

**Comment by mikhailramalho** [comment] 2021-02-03 17:29
Right, he's the minimal example I could create:
```
namespace STP {
#include <c_interface.h>
}

#include <memory>
#include <cassert>
#include <iostream>

int main()
{
  auto Context = std::make_shared<STP::VC>(STP::vc_createValidityChecker());

  // #1 create bv of size 10
  auto x = STP::vc_bvConstExprFromStr(*Context, "0000000001");

  // #2 create bv of size 2
  auto y = STP::vc_bvSignExtend(*Context, STP::vc_bvConstExprFromStr(*Context, "10000010"), 2);

  // #3 sub accepts the two bv with different bitwidth.
  auto sub = STP::vc_bvMinusExpr(*Context, 10, x, y);
  
  auto f = STP::vc_varExpr(*Context, "f", STP::vc_bvType(*Context, 10));
  
  STP::vc_assertFormula(*Context, STP::vc_eqExpr(*Context, f, sub));
  auto res = STP::vc_query(*Context, STP::vc_falseExpr(*Context));
  assert(!res);
 
  STP::vc_printAsserts(*Context);
  
  char *buf;
  unsigned long len;
  STP::vc_printCounterExampleToBuffer(*Context, &buf, &len);
  std::cerr << buf << '\n';
  free(buf); 
}
```

I've added a bunch of assertions in my code, so it was not reaching the `vc_bvSignExtend` anymore, it was triggering an error in `vc_bvMinusExpr`.

Maybe sub is casting the variable x to the bitwidth of y?

**Comment by mikhailramalho** [comment] 2021-02-03 17:30
The formula andcex I get is:
```
ASSERT( (0b1111111111 = f
) );

COUNTEREXAMPLE BEGIN: 
ASSERT( f = 0b1111111111 );
COUNTEREXAMPLE END: 
```

**Comment by andrewvaughanj** [comment] 2021-02-03 18:03
So there's a few things going on here:

- In your example, this (again) goes through the constant evaluator that doesn't really do any type checking -- I'm not sure how this is handled with overflow/underflow/etc.
- When you create a non-constant term, subtract is written into `BVPLUS` with the second argument being `BVUMINUS` -- the creation of the `BVUMINUS` *does* (silently) expand the the second argument into the width of the requested width of the overall expression
- If you flip your arguments (with one being non-constant) such that your terms are width 2 and 10 (rather than 10 and 2), you'll get an exception in the API

I agree that this isn't great; my suggestion here would be to check that params passed in to `vc_bvMinusExpr` are of the same width -- would this be better for you? Hopefully there aren't users of STP who are "abusing" this behaviour ...

**Comment by mikhailramalho** [comment] 2021-02-06 15:35
> I agree that this isn't great; my suggestion here would be to check that params passed in to `vc_bvMinusExpr` are of the same width -- would this be better for you? Hopefully there aren't users of STP who are "abusing" this behaviour ...

**Comment by mikhailramalho** [comment] 2021-02-06 15:37
> I agree that this isn't great; my suggestion here would be to check that params passed in to `vc_bvMinusExpr` are of the same width -- would this be better for you? Hopefully there aren't users of STP who are "abusing" this behaviour ...

Yeah, that sounds reasonable. That's actually how I found the issue: I added a bunch of assertions to validate the expr operands before actually calling the solver.

**Closed** 2022-05-13 06:06 UTC
