### ISSUE TITLE
Cmake error (archlinux 64-bit)

### ISSUE THREAD

**Issue by bytbox** [stp/stp#156] opened 2015-01-28 19:20 UTC
I cannot escape this cmake error:

    -- The C compiler identification is GNU 4.9.2
    -- The CXX compiler identification is GNU 4.9.2
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- You can choose the type of build, options are:Debug;Release;RelWithDebInfo;MinSizeRel
    -- Doing a RelWithDebInfo build
    -- Building shared library currently broken due to mix of C++/C code
    -- Performing Test HAVE_FLAG_-fPIC
    -- Performing Test HAVE_FLAG_-fPIC - Success
    -- Performing Test HAVE_FLAG_STD_GNUCPP11
    -- Performing Test HAVE_FLAG_STD_GNUCPP11 - Success
    -- Performing Test HAVE_FLAG_STD_GNUCPP0X
    -- Performing Test HAVE_FLAG_STD_GNUCPP0X - Success
    -- Performing Test HAVE_FLAG_STD_CPP11
    -- Performing Test HAVE_FLAG_STD_CPP11 - Success
    -- Performing Test HAVE_FLAG_STD_CPP0X
    -- Performing Test HAVE_FLAG_STD_CPP0X - Success
    -- Performing Test HAVE_FLAG_STDLIB_LIBCPP
    -- Performing Test HAVE_FLAG_STDLIB_LIBCPP - Failed
    -- Performing Test HAVE_FLAG_-Wall
    -- Performing Test HAVE_FLAG_-Wall - Success
    -- Performing Test HAVE_FLAG_-pedantic
    -- Performing Test HAVE_FLAG_-pedantic - Success
    -- Performing Test HAVE_FLAG_-Wunused
    -- Performing Test HAVE_FLAG_-Wunused - Success
    -- Performing Test HAVE_FLAG_-Wsign-compare
    -- Performing Test HAVE_FLAG_-Wsign-compare - Success
    -- Performing Test HAVE_FLAG_-Wtype-limits
    -- Performing Test HAVE_FLAG_-Wtype-limits - Success
    -- Performing Test HAVE_FLAG_-Wuninitialized
    -- Performing Test HAVE_FLAG_-Wuninitialized - Success
    -- Performing Test HAVE_FLAG_-Wno-deprecated
    -- Performing Test HAVE_FLAG_-Wno-deprecated - Success
    -- Performing Test HAVE_FLAG_-Wstrict-aliasing
    -- Performing Test HAVE_FLAG_-Wstrict-aliasing - Success
    -- Performing Test HAVE_FLAG_-Wpointer-arith
    -- Performing Test HAVE_FLAG_-Wpointer-arith - Success
    -- Performing Test HAVE_FLAG_-Wheader-guard
    -- Performing Test HAVE_FLAG_-Wheader-guard - Failed
    -- Checking for C++ hash_set implementation...
    -- Performing Test HAVE_HASH_SET_STD
    -- Performing Test HAVE_HASH_SET_STD - Success
    -- C++ hash_set found as std::unordered_set in <unordered_set>
    -- Checking for C++ hash_multiset implementation...
    -- Performing Test HAVE_HASH_MULTISET_STD
    -- Performing Test HAVE_HASH_MULTISET_STD - Success
    -- C++ hash_multiset found as std::unordered_multiset in <unordered_set>
    -- Checking for C++ hash_map implementation...
    -- Performing Test HAVE_HASH_MAP_STD
    -- Performing Test HAVE_HASH_MAP_STD - Success
    -- C++ hash_map found as std::unordered_map in <unordered_map>
    -- Boost version: 1.57.0
    -- Found the following Boost libraries:
    --   program_options
    CMake Warning at CMakeLists.txt:266 (find_package):
      Could not find a package configuration file provided by "cryptominisat4"
      with any of the following names:
    
        cryptominisat4Config.cmake
        cryptominisat4-config.cmake
    
      Add the installation prefix of "cryptominisat4" to CMAKE_PREFIX_PATH or set
      "cryptominisat4_DIR" to a directory containing one of the above files.  If
      "cryptominisat4" provides a separate development package or SDK, be sure it
      has been installed.
    
    
    CMake Warning at CMakeLists.txt:273 (message):
      CryptoMiniSat4 or C++11 support not found, not allowing --cryptominisat4
      option
    
    
    -- Found BISON: /usr/bin/bison (found version "3.0.2") 
    -- Found FLEX: /usr/bin/flex (found version "2.5.39") 
    -- Found PythonInterp: /usr/bin/python (found version "3.4.2") 
    -- Found Perl: /usr/bin/perl (found version "5.20.1") 
    -- Performing Test HAVE_C_FLAG_-fPIC
    -- Performing Test HAVE_C_FLAG_-fPIC - Success
    CMake Warning (dev) at bindings/python/stp/CMakeLists.txt:4 (get_target_property):
      Policy CMP0026 is not set: Disallow use of the LOCATION target property.
      Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
      command to set the policy and suppress this warning.
    
      The LOCATION property should not be read from target "libstp".  Use the
      target name directly with add_custom_command, or use the generator
      expression $<TARGET_FILE>, as appropriate.
    
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Detected python site package directory /usr/lib/python3.4/site-packages
    CMake Warning (dev) at bindings/python/stp/CMakeLists.txt:41 (get_target_property):
      Policy CMP0026 is not set: Disallow use of the LOCATION target property.
      Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
      command to set the policy and suppress this warning.
    
      The LOCATION property should not be read from target "libstp".  Use the
      target name directly with add_custom_command, or use the generator
      expression $<TARGET_FILE>, as appropriate.
    
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    CMake Warning at CMakeLists.txt:348 (message):
      Testing is disabled
    
    
    -- Configuring done
    CMake Error: CMake can not determine linker language for target: libstp
    CMake Error in lib/CMakeLists.txt:
      Exporting the target "libstp" is not allowed since its linker language
      cannot be determined
    
    
    CMake Error: CMake can not determine linker language for target: libstp
    CMake Error in lib/CMakeLists.txt:
      Exporting the target "libstp" is not allowed since its linker language
      cannot be determined
    
    
    CMake Error: Cannot determine link language for target "libstp".
    CMake Error in lib/CMakeLists.txt:
      Exporting the target "libstp" is not allowed since its linker language
      cannot be determined
    
    
    CMake Error in lib/CMakeLists.txt:
      Exporting the target "libstp" is not allowed since its linker language
      cannot be determined
    
    
    -- Generating done
    -- Build files have been written to: /tmp/stp/build
    
This is with cmake 3.1.0.

**Comment by delcypher** [comment] 2015-01-28 19:38
Hi @bytbox . Thanks reporting. I'm also on Arch and I can reproduce this. Something must of changed between cmake 3.1.0 and cmake 3.0 because the last time I built STP was when I was using cmake 3.0 and I didn't have any problems.

To work around this please add this line to the bottom of ``lib/CMakeLists.txt``

```
set_target_properties(libstp PROPERTIES LINKER_LANGUAGE CXX)
```

this fixes the configure but something still seems to be broken because now linking fails because for some reason the dynamic library is missing the symbols :( . The static library seems fine so run cmake like so to have the stp executable link against the static library only

```
cmake -DBUILD_SHARED_LIBS=OFF -DENABLE_PYTHON_INTERFACE=OFF /path/to/stp/source/code
```

**Comment by delcypher** [comment] 2015-02-17 00:47
@bytbox I just started looking at this again. The issue seems to have gone away with ``cmake 3.1.3-1`` in Arch. Can you confirm?

If so I'll close this issue.

**Comment by bytbox** [comment] 2015-02-17 01:49
Looks fixed, excellent! Sadly, I can't figure out which cmake bug on mantisbt (or which commit) is relevant. Ah well.

**Comment by delcypher** [comment] 2015-02-17 11:11
@bytbox Thanks for confirming.

**Closed by delcypher** 2015-02-17 11:11 UTC
