### ISSUE TITLE
Cannot build STP from Git in Ubuntu 14.04 x86_64

### ISSUE THREAD

**Issue by joxeankoret** [stp/stp#172] opened 2015-04-13 16:46 UTC
Hi,

I'm trying to compile STP from Git but I'm encountering some errors (using gcc-4.5 to gcc-4.8, it doesn't matter which compiler I use):

```
[ 96%] Building CXX object lib/Sat/CMakeFiles/sat.dir/MinisatCore.cpp.o
/home/joxean/devel/klee/stp/lib/Sat/MinisatCore.cpp: In member function ‘virtual bool stp::MinisatCore::solve(bool&)’:
/home/joxean/devel/klee/stp/lib/Sat/MinisatCore.cpp:74:23: error: expected unqualified-id before ‘(’ token
/home/joxean/devel/klee/stp/lib/Sat/MinisatCore.cpp:78:26: error: expected unqualified-id before ‘(’ token
/home/joxean/devel/klee/stp/lib/Sat/MinisatCore.cpp: In member function ‘virtual void stp::MinisatCore::printStats()’:
/home/joxean/devel/klee/stp/lib/Sat/MinisatCore.cpp:108:6: error: ‘class Minisat::Solver’ has no member named ‘printStats’
/home/joxean/devel/klee/stp/lib/Sat/MinisatCore.cpp: In member function ‘virtual bool stp::MinisatCore::solve(bool&)’:
/home/joxean/devel/klee/stp/lib/Sat/MinisatCore.cpp:79:1: warning: control reaches end of non-void function [-Wreturn-type]
make[2]: *** [lib/Sat/CMakeFiles/sat.dir/MinisatCore.cpp.o] Error 1
make[1]: *** [lib/Sat/CMakeFiles/sat.dir/all] Error 2
make: *** [all] Error 2
```

Am I doing something wrong?

**Comment by msoos** [comment] 2015-04-13 20:50
OK, I can reproduce it, it's from MiniSat that's installed by the package manager. Let me try to deal with this :)

**Comment by msoos** [comment] 2015-04-13 22:20
Hey, can you please check if this fix indeed solves the issue for you? I'm closing temporarily because I could reproduce the issue but with the fix it seems fine. Please get back to me so I know :)

Thanks for the bugreport, it really helped!

Cheers,

Mate

**Closed by msoos** 2015-04-13 22:20 UTC

**Comment by joxeankoret** [comment] 2015-04-14 07:38
It seems to be working now, thanks!

**Comment by msoos** [comment] 2015-04-14 22:13
Thanks for getting back to me and good luck using the system! If you encounter any issue, or have a suggestion, please open an issue! Cheers!
